version: '3.1'

services:
  db:
    # TBachminski:
    # Trying to use the latest version of mysql causes the database
    # container to throw a hissy fit about "mbind: Operation not permitted",
    # which in turn brings up database container startup time from about
    # 1-2 minutes to over 5 minutes.
    #
    # Use a specific, older version of mysql to avoid this.
    # Alternatively can use a custom security profile for Docker,
    # but this is good enough for now.
    # https://github.com/docker-library/mysql/issues/303
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sqldb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass

  spring-app:
    image: tbachminski/inteca-eval-spring
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: sqldb
      DATABASE_USER: dbuser
      DATABASE_PASSWORD: dbpass

  angular-app:
    image: tbachminski/inteca-eval-angular
    restart: always
    ports:
      - 4200:80
