version: '3.1'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sqldb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass

  spring-app:
    image: kartoflane/inteca-eval-spring
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:8080
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: sqldb
      DATABASE_USER: dbuser
      DATABASE_PASSWORD: dbpass
